sudo: required

language: python
python: "2.7"

services:
  - docker

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install sshpass

  - ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa

  - docker pull tutum/centos:centos7
  - docker run -d -p 0.0.0.0:2222:22 -e ROOT_PASS="password" -e AUTHORIZED_KEYS="`cat ~/.ssh/id_rsa.pub`" tutum/centos:centos7
  - ssh root@localhost -vvv -p 2222 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "echo -n systemd > /proc/1/comm; exit"

  - docker pull tutum/centos:centos6
  - docker run -d -p 0.0.0.0:2223:22 -e ROOT_PASS="password" -e AUTHORIZED_KEYS="`cat ~/.ssh/id_rsa.pub`" tutum/centos:centos6

install:
  - pip install ansible

  # add an ansible.cfg file to pick up the roles path
  - printf '[defaults]\nroles_path = ../\nhost_key_checking = false' > ansible.cfg

script:
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check
  - ansible-playbook -i tests/inventory tests/test.yml

after_failure:
  - ssh root@localhost -p 2222 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "systemctl list-unit-files | grep httpd; exit"
