sudo: required

language: python
python: "2.7"

services:
  - docker

before_install:
  - docker pull centos:7
  - docker run -d -p 127.0.0.1:2222:22 centos:7 /bin/sh -c "yum install -y passwd"
  - docker ps -a

install:
  - pip install ansible

  # add an ansible.cfg file to pick up the roles path
  - printf '[defaults]\nroles_path = ../' > ansible.cfg

