sudo: required

language: python
python: "2.7"

services:
  - docker

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install dpkg-dev virtualbox-dkms
  - wget https://releases.hashicorp.com/vagrant/1.7.4/vagrant_1.7.4_x86_64.deb
  - wget http://download.virtualbox.org/virtualbox/5.0.10/virtualbox-5.0_5.0.10-104061~Ubuntu~precise_amd64.deb
  - sudo apt-get install dkms
  - sudo dpkg -i vagrant_1.7.4_x86_64.deb
  - sudo dpkg -i virtualbox-5.0_5.0.10-104061~Ubuntu~precise_amd64.deb
  - sudo apt-get install linux-headers-$(uname -r)
  - sudo dpkg-reconfigure virtualbox-dkms
  - sudo /etc/init.d/vboxdrv setup


install:
  - pip install ansible

  # add an ansible.cfg file to pick up the roles path
  - printf '[defaults]\nroles_path = ../\nhost_key_checking = false' > ansible.cfg

  - vagrant up --no-provision

script:
  - ansible-playbook -i tests/vagrant_inventory tests/test.yml --syntax-check
  - ansible-playbook -i tests/vagrant_inventory tests/test.yml
