sudo: required

language: python
python: "2.7"

services:
  - docker

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install virtualbox vagrant virtualbox-dkms


install:
  - pip install ansible

  # add an ansible.cfg file to pick up the roles path
  - printf '[defaults]\nroles_path = ../\nhost_key_checking = false' > ansible.cfg

  - vagrant up --no-provision

script:
  - ansible-playbook -i tests/vagrant_inventory tests/test.yml --syntax-check
  - ansible-playbook -i tests/vagrant_inventory tests/test.yml
