sudo: required

language: python
python: "2.7"

services:
  - docker

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install sshpass

  - docker pull tutum/centos:centos7
  - docker run -d -p 0.0.0.0:2222:22 -e ROOT_PASS="password" tutum/centos:centos7
  - docker ps -a

install:
  - pip install ansible

  # add an ansible.cfg file to pick up the roles path
  - printf '[defaults]\nroles_path = ../\nhost_key_checking = false' > ansible.cfg

script:
  - sshpass -p password ssh root@localhost -p 2222 -o StrictHostKeyChecking=no "exit"
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check
  - ansible-playbook -i tests/inventory tests/test.yml

after_failure:
  - sshpass -p password ssh root@localhost -p 2222 -o StrictHostKeyChecking=no "systemctl list-unit-files | grep httpd; exit"
