---

- name: Apache 2.4 SCL | enable apache vhosts
  template:
    src: vhost.conf.j2
    dest: "{{ apache24_scl_conf_d_directory_path }}/{{ item.priority | default('10') }}-{{ item.server_name }}.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart apache24
  with_items: apache24_scl_vhosts
  when: apache24_scl_manage_vhosts
  tags:
    - scl
    - apache
    - apache24
    - webserver
    - vhost
    - config
    - configuration

- name: Apache 2.4 SCL | disable apache vhosts
  file:
    path: "{{ apache24_scl_conf_d_directory_path }}/{{ item.priority | default('10') }}-{{ item.server_name }}.conf"
    state: absent
  notify: restart apache24
  with_items: apache24_scl_disabled_vhosts
  when: apache24_scl_manage_vhosts
  tags:
    - scl
    - apache
    - apache24
    - webserver
    - vhost
    - config
    - configuration
